version: '3.7'

services:
  web:
    build: ./backend
    image: uzman
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY: minio
      AWS_SECRET_KEY: minio123
      AWS_BUCKET_NAME: images
      PYTHONUNBUFFERED: 1
    depends_on:
      - migration
      - pgdb
      - minio

  migration:
    image: uzman
    command: bash -c "python manage.py migrate --noinput && python manage.py fill_db"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      pgdb:
        condition: service_healthy
    links:
      - pgdb

  minio:
    hostname: minio/minio:latest
    image: quay.io/minio/minio:RELEASE.2022-10-15T19-57-03Z
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  createbucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 minio minio123;
      /usr/bin/mc mb s3/images;
      /usr/bin/mc anonymous set public s3/images;
      "

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

  pgdb:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - type: volume
        source: pgdbdata
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
       - pgadmin:/var/www/nest_test/docker-volumes/pgadmin
       - ./servers.json:/pgadmin4/servers.json
       - ./pgpass:/pgpass
    ports:
      - 127.0.0.1:5050:80
    restart: unless-stopped

  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://django:8000

volumes:
  minio-data:
  pgdbdata: null
  pgadmin:
